### ISSUE TITLE
World is not being generated. Can this be enabled?

### ISSUE THREAD

**Issue by samfces** [Paul19988/Advanced-Slime-World-Manager#91]
**Describe the issue**
When we walk to the area of the world that is not generated, the chunks are not generated automaticallyas we might find in a normal MC world.

In case this is not a bug, would there be any possibility to activate this function?

**Spigot version**
Purpur 1.17.1

**Plugin version**
2.7.0

**Comment by ComputerNerd100** [comment]
@samfces We don't officially support Purpur
Please could you test with Paper. If you are still experiencing this issue on Paper, please update this issue.

**Comment by samfces** [comment]
@ComputerNerd100 I have switched to Paper 1.17.1 and the problem persists. I have to comment that the world has been pregenerated up to a certain coordinate (500 blocks radius from the center of the world) so I don't know if this has something to do with it.

**UPDATE**: I found the cut at coordinates that do not correspond to that pregeneration.

**Comment by Paul19988** [comment]
ASWM does not support normal worlds, it is not intended to support normal generation.

**Comment by b0ykoe** [comment]
ASWM does not generate normal terrain.

**Comment by samfces** [comment]
And would there be any way to make ASWM support this feature even if I have to code it for my server or the ASWM code structure does not allow it?

**Comment by Paul19988** [comment]
ASWM does not support anything outside of small Minigames and skyblock, the world structure just isn't designed to support anything bigger

**Comment by ComputerNerd100** [comment]
@samfces Why do you need this feature for ASWM?
If there's a genuine use case I'd be keen to know if its something we can look into, but ASWM at its heart is not designed to deal with normal minecraft worlds, it deals with worlds in the SLIME format which are primarily minigame worlds
What you're asking for sounds a little out-of-scope for ASWM - you'd need to look towards Multiverse for what you want provided I've understood you correctly so far

**Comment by samfces** [comment]
We are trying to do something similar to what Hypixel has done with Skyblock but changing the SkyBlock worlds for pregenerated Survival worlds of very limited size for this gamemode (1000x1000). 

In this game mode, it is necessary for players to be able to explore so, being such small worlds, we have several pregenerated worlds of 1000x1000 with a block limit of 8000x8000. This is why I am asking about the activation of world generation.

When making this system we need worlds to be transferred quickly and easily between servers without having to compress and decompress worlds and without causing a major performance impact, so ASWM is our only known escape route to this problem.

For these reasons and according to @ComputerNerd100, it is not viable to use Multiverse to solve the problems I mentioned.

**Comment by ComputerNerd100** [comment]
@samfces 
Hmm I do completely get what you're saying here
Its an interesting use case. So basically you already have the 1000x1000 defined, but when going outside of that area (to the 8000x8000 limit) you want it to generate the chunks on the fly in a similar fashion to normal world generation.

The issue here is ASWM does not support any form of terrain generation and making it do this isn't feasible at the moment. However, I do like your suggestion and it's definitely an interesting concept. While I can't promise anything in the immediate future, I've noted this as a potential for increasing the feature scope later down the line.

Sadly I can't really advise a best alternate solution for you right now. However I hope you can find something that works for you and if you need anything please let me know. Can I also suggest joining our Discord if you haven't already: https://discord.gg/YevvsMa
